### ISSUE TITLE
High Complexity for new Diagrams

### ISSUE THREAD

**Issue by MZeisler** [borkdominik/bigUML#108]
Adding new diagrams and diagram parts is associated with a very high complexity. To have a reasonably working basis of a node / an edge, a lot of different files must be created. In the end, you always forget something and then have to debug for a long time until you really have implemented all files and required functions with the right types.
What would help here, for example, is if one could perhaps bundle more logic in one file instead of outsourcing any logic, no matter how small, to its own files. Example CRUD, for a single node / a single edge it needs for Create, Update and Delete 3 x 3 = 9 files. For 5 nodes and 5 edges that's 90 files. And this does not include any of the many other required files.

**Comment by haydar-metin** [comment]
Thank you very much for the feedback @Pfingstfrosch!

I will focus on reducing the required complexity in the next release(s). Unfortunately, to allow flexibility, those files were necessary. However, to allow easier usage, I will provide new ways to abstract / hide those files and thus reduce the necessary file count.

**Comment by Pfingstfrosch** [comment]
@haydar-metin Thanks for the quick reply, looking forward to it.
