### ISSUE TITLE
Selecting types for properties is confusing and mistranslated

### ISSUE THREAD

**Issue by CorneliusCornbread** [borkdominik/bigUML#137]
Attempting to change the type of a property after deleting the undefined pops up the message "Please select from the dropdown (strg + space)"

Googling 'strg' shows that this is a mistranslation from German for the CTRL key. Moreover, just being able to type and the suggestions come up like normal would be really nice. _Having_ to _absolutely_ use the dropdown just adds an unnecessary keypress. 

Just make the dropdown appear as soon as you edit the field. And also allows users to fully type out the name and as long as it's correct let it just take it for the type.

**Comment by haydar-metin** [comment]
Hey @CorneliusCornbread!

Thank you for the feedback. You are absolutely correct. This part still needs to be reworked to provide a better user experience. I thought about using an autocomplete there and also for other places (e.g., property palette) too. 

Do you have a preference what to do if two elements have the same name?

**Comment by CorneliusCornbread** [comment]
> Hey @CorneliusCornbread!
> 
> Thank you for the feedback. You are absolutely correct. This part still needs to be reworked to provide a better user experience. I thought about using an autocomplete there and also for other places (e.g., property palette) too.
> 
> Do you have a preference what to do if two elements have the same name?

I don't have a particular preference but in my mind, it makes the most sense if it underlines the two elements that have a duplicated name, as well as all the elements referencing these duplicated elements. Otherwise in terms of elements that are nested but have the same name then they should be fully qualified when nested. Ex `Class1.EnumValue` and `Class2.EnumValue` would be the name for nested enums or something.
