### ISSUE TITLE
UML example models

### ISSUE THREAD

**Issue by soerendomroes** [borkdominik/bigUML#164]
Hi, I want to try out the bigUML VS Code extension, but I am missing some examples or a hello world model to get familiar with the syntax.

Just creating an ".uml" file results in a GLSP error and infinite loading.
![image](https://github.com/user-attachments/assets/0507695c-760a-4b76-928f-d91c6bb46153)

Am I using it wrong or missing something else?

**Comment by haydar-metin** [comment]
Hey @soerendomroes! 

You can create a new model by either using the following command (ctrl + shift + p):

![image](https://github.com/user-attachments/assets/a5ef9b83-f117-40ae-b057-a5b8c36d065c)

Or by `File -> New File`.

This should create the necessary files for you and open the editor directly.

Thanks for testing `bigUML`, if you have any other questions, just ask me here :+1:

**Comment by borkdominik** [comment]
Thanks for your question @soerendomroes, I saw @haydar-metin was faster with the response/help.
Let us know if you face further issues and always have in mind, this is ongoing work so we appreciate every feedback and bug report.
- Dominik
